### 插件设置
# 渲染精度
renderScale: 150
# 系统状态是否所有人可用
SystemStatusAll: false
# Redis状态是否所有人可用
RedisStatusAll: false
# 是否启用前台重启劫持(仅测试Miao-Yunzai),只支持Windows系统
MEMZRestart: false
# 是否自动杀死chrome进程
kallChromeEnabled: false
# 杀死chrome进程cron
kallChromeCron: "0 0 0,12,7,19 * * ?"
# 自动点赞 主人默认在点赞名单
AutoLike: true
# 自动点赞列表
AutoLikeList: []
# 谁艾特我保留时长(小时)
whoAtmeTime: 24
# 主人被禁言自动解禁
helpMaster: true
# 主人被禁言自动解禁提示语
helpMasterText: "我来救你了主人！！！！！"
# 主人被禁言救不了提示语
nohelpMasterText: "主人~我救不了你啊！"
# 艾特全体文本
atalltext: "不🈷️"
# 艾特全体分片
atChunkSize: 40
# QQInfo 查询
qqInfo: true

### 工具设置
# 是否所有人可用Whois
WhoisAll: true
# 是否所有人可用SEO
SeoAll: true
# 是否所有人可用HTTP状态查询
httpStatusAll: true
# 是否所有人可用备案查询
icpBeianAll: true
# 备案接口
icpBeian: 1
# 是否所有人可用域名查询价格
DomainMinPricingAll: true
# 是否所有人可用网页截图
webpage: false
# 是否所有人可用Ping
PingAll: true
# Ping是否使用代理
PingProxy: false
# Ping代理设置
PingProxyAddress: ""
# Ping接口
#*0为`本地`Ping测速
#*1为`炸了吗`测速截图
#*2为`ITdog`测速截图
#*3为`Blogs.ink`接口
#*4为`UAPIs.cn`接口
#*5为`远梦API`接口
#*6为`远昔API`接口
#*7为`倾梦API`接口
PingApi: 2
# Ipinfo是否所有人可用
IpinfoAll: true
# Ipinfo使用的接口
#* 1为`ipinfo.io`接口
#* 2为`bilibili`接口
#* 3为`ip.sb`接口
#* 4为`ip-api.com`接口
#* 5为`Ip2locationIo`接口
#* 6为`ipApiIs`接口
#* 7为`InIp.In`接口
#* 8为`Mir6`接口
#* 9为`cip.cc`接口
IpinfoApi: 2
# Ping功能Ipinfo.io的token
IpinfoToken: ""
# 是否所有人可用Unicode编码解码
UnicodeAll: true
# 是否所有人可用url编码解码
UrlAll: true
# 是否所有人可用进制转换
BaseConversionAll: true
# 是否所有人可用文本去空格
removeSpacesAll: false
# 是否所有人可用Hex编码解码
HexOperationAll: false
# 是否所有人可用Punycode编码解码
PunycodeOperationAll: false
# 是否所有人可用获取网站图标
getFaviconAll: true

### 网络搜索设置
# 是否开启搜影视
SearchMovie: true
# 是否开启搜资源
SearchResource: true
# 搜资源阈值,模糊匹配的宽松度,范围从 0 到 1，值越小，表示匹配的结果越严格，越大则表示匹配的宽松度越高。
threshold: 0.3
# 申请游戏是否开启
apply_game: true
# 是否开启磁力搜索
SearchMagnet: false

### 定时群发设置
# 定时群发开关
GroupScheduler: false
# 群发白名单bot
GroupSchedulerWhiteBotList: []
# 群发黑名单bot
GroupSchedulerBlackBotList: []
# 定时群发CRON表达式
GroupSchedulerCron: "0 0 1 * *?" #默认每天1点
# 定时群发内容
GroupSchedulerMsg: "#全部赞我"
# 定时群发群组
GroupSchedulerGroup: []